package me.fan87.spookysky.client.mapping.impl.item


import me.fan87.spookysky.client.mapping.ClassMapping
import me.fan87.spookysky.client.mapping.FieldMapping
import me.fan87.spookysky.client.mapping.WrapperClass


object MapItems : ClassMapping<Items>() {
    override fun getWrapperClass(): Class<Items> {
        return Items::class.java
    }

    override val humanReadableName: String
        get() = "Items"

    val iron_pickaxe = ItemsMapping("iron_pickaxe")
    val iron_shovel = ItemsMapping("iron_shovel")
    val iron_axe = ItemsMapping("iron_axe")
    val flint_and_steel = ItemsMapping("flint_and_steel")
    val apple = ItemsMapping("apple")
    val bow = ItemsMapping("bow")
    val arrow = ItemsMapping("arrow")
    val coal = ItemsMapping("coal")
    val diamond = ItemsMapping("diamond")
    val iron_ingot = ItemsMapping("iron_ingot")
    val gold_ingot = ItemsMapping("gold_ingot")
    val iron_sword = ItemsMapping("iron_sword")
    val wooden_sword = ItemsMapping("wooden_sword")
    val wooden_shovel = ItemsMapping("wooden_shovel")
    val wooden_pickaxe = ItemsMapping("wooden_pickaxe")
    val wooden_axe = ItemsMapping("wooden_axe")
    val stone_sword = ItemsMapping("stone_sword")
    val stone_shovel = ItemsMapping("stone_shovel")
    val stone_pickaxe = ItemsMapping("stone_pickaxe")
    val stone_axe = ItemsMapping("stone_axe")
    val diamond_sword = ItemsMapping("diamond_sword")
    val diamond_shovel = ItemsMapping("diamond_shovel")
    val diamond_pickaxe = ItemsMapping("diamond_pickaxe")
    val diamond_axe = ItemsMapping("diamond_axe")
    val stick = ItemsMapping("stick")
    val bowl = ItemsMapping("bowl")
    val mushroom_stew = ItemsMapping("mushroom_stew")
    val golden_sword = ItemsMapping("golden_sword")
    val golden_shovel = ItemsMapping("golden_shovel")
    val golden_pickaxe = ItemsMapping("golden_pickaxe")
    val golden_axe = ItemsMapping("golden_axe")
    val string = ItemsMapping("string")
    val feather = ItemsMapping("feather")
    val gunpowder = ItemsMapping("gunpowder")
    val wooden_hoe = ItemsMapping("wooden_hoe")
    val stone_hoe = ItemsMapping("stone_hoe")
    val iron_hoe = ItemsMapping("iron_hoe")
    val diamond_hoe = ItemsMapping("diamond_hoe")
    val golden_hoe = ItemsMapping("golden_hoe")
    val wheat_seeds = ItemsMapping("wheat_seeds")
    val wheat = ItemsMapping("wheat")
    val bread = ItemsMapping("bread")
    val leather_helmet = ItemsMapping("leather_helmet")
    val leather_chestplate = ItemsMapping("leather_chestplate")
    val leather_leggings = ItemsMapping("leather_leggings")
    val leather_boots = ItemsMapping("leather_boots")
    val chainmail_helmet = ItemsMapping("chainmail_helmet")
    val chainmail_chestplate = ItemsMapping("chainmail_chestplate")
    val chainmail_leggings = ItemsMapping("chainmail_leggings")
    val chainmail_boots = ItemsMapping("chainmail_boots")
    val iron_helmet = ItemsMapping("iron_helmet")
    val iron_chestplate = ItemsMapping("iron_chestplate")
    val iron_leggings = ItemsMapping("iron_leggings")
    val iron_boots = ItemsMapping("iron_boots")
    val diamond_helmet = ItemsMapping("diamond_helmet")
    val diamond_chestplate = ItemsMapping("diamond_chestplate")
    val diamond_leggings = ItemsMapping("diamond_leggings")
    val diamond_boots = ItemsMapping("diamond_boots")
    val golden_helmet = ItemsMapping("golden_helmet")
    val golden_chestplate = ItemsMapping("golden_chestplate")
    val golden_leggings = ItemsMapping("golden_leggings")
    val golden_boots = ItemsMapping("golden_boots")
    val flint = ItemsMapping("flint")
    val porkchop = ItemsMapping("porkchop")
    val cooked_porkchop = ItemsMapping("cooked_porkchop")
    val painting = ItemsMapping("painting")
    val golden_apple = ItemsMapping("golden_apple")
    val sign = ItemsMapping("sign")
    val oak_door = ItemsMapping("wooden_door")
    val spruce_door = ItemsMapping("spruce_door")
    val birch_door = ItemsMapping("birch_door")
    val jungle_door = ItemsMapping("jungle_door")
    val acacia_door = ItemsMapping("acacia_door")
    val dark_oak_door = ItemsMapping("dark_oak_door")
    val bucket = ItemsMapping("bucket")
    val water_bucket = ItemsMapping("water_bucket")
    val lava_bucket = ItemsMapping("lava_bucket")
    val minecart = ItemsMapping("minecart")
    val saddle = ItemsMapping("saddle")
    val iron_door = ItemsMapping("iron_door")
    val redstone = ItemsMapping("redstone")
    val snowball = ItemsMapping("snowball")
    val boat = ItemsMapping("boat")
    val leather = ItemsMapping("leather")
    val milk_bucket = ItemsMapping("milk_bucket")
    val brick = ItemsMapping("brick")
    val clay_ball = ItemsMapping("clay_ball")
    val reeds = ItemsMapping("reeds")
    val paper = ItemsMapping("paper")
    val book = ItemsMapping("book")
    val slime_ball = ItemsMapping("slime_ball")
    val chest_minecart = ItemsMapping("chest_minecart")
    val furnace_minecart = ItemsMapping("furnace_minecart")
    val egg = ItemsMapping("egg")
    val compass = ItemsMapping("compass")
    val fishing_rod = ItemsMapping("fishing_rod")
    val clock = ItemsMapping("clock")
    val glowstone_dust = ItemsMapping("glowstone_dust")
    val fish = ItemsMapping("fish")
    val cooked_fish = ItemsMapping("cooked_fish")
    val dye = ItemsMapping("dye")
    val bone = ItemsMapping("bone")
    val sugar = ItemsMapping("sugar")
    val cake = ItemsMapping("cake")
    val bed = ItemsMapping("bed")
    val repeater = ItemsMapping("repeater")
    val cookie = ItemsMapping("cookie")
    val filled_map = ItemsMapping("filled_map")
    val shears = ItemsMapping("shears")
    val melon = ItemsMapping("melon")
    val pumpkin_seeds = ItemsMapping("pumpkin_seeds")
    val melon_seeds = ItemsMapping("melon_seeds")
    val beef = ItemsMapping("beef")
    val cooked_beef = ItemsMapping("cooked_beef")
    val chicken = ItemsMapping("chicken")
    val cooked_chicken = ItemsMapping("cooked_chicken")
    val mutton = ItemsMapping("mutton")
    val cooked_mutton = ItemsMapping("cooked_mutton")
    val rabbit = ItemsMapping("rabbit")
    val cooked_rabbit = ItemsMapping("cooked_rabbit")
    val rabbit_stew = ItemsMapping("rabbit_stew")
    val rabbit_foot = ItemsMapping("rabbit_foot")
    val rabbit_hide = ItemsMapping("rabbit_hide")
    val rotten_flesh = ItemsMapping("rotten_flesh")
    val ender_pearl = ItemsMapping("ender_pearl")
    val blaze_rod = ItemsMapping("blaze_rod")
    val ghast_tear = ItemsMapping("ghast_tear")
    val gold_nugget = ItemsMapping("gold_nugget")
    val nether_wart = ItemsMapping("nether_wart")
    val potionitem = ItemsMapping("potion")
    val glass_bottle = ItemsMapping("glass_bottle")
    val spider_eye = ItemsMapping("spider_eye")
    val fermented_spider_eye = ItemsMapping("fermented_spider_eye")
    val blaze_powder = ItemsMapping("blaze_powder")
    val magma_cream = ItemsMapping("magma_cream")
    val brewing_stand = ItemsMapping("brewing_stand")
    val cauldron = ItemsMapping("cauldron")
    val ender_eye = ItemsMapping("ender_eye")
    val speckled_melon = ItemsMapping("speckled_melon")
    val spawn_egg = ItemsMapping("spawn_egg")
    val experience_bottle = ItemsMapping("experience_bottle")
    val fire_charge = ItemsMapping("fire_charge")
    val writable_book = ItemsMapping("writable_book")
    val written_book = ItemsMapping("written_book")
    val emerald = ItemsMapping("emerald")
    val item_frame = ItemsMapping("item_frame")
    val flower_pot = ItemsMapping("flower_pot")
    val carrot = ItemsMapping("carrot")
    val potato = ItemsMapping("potato")
    val baked_potato = ItemsMapping("baked_potato")
    val poisonous_potato = ItemsMapping("poisonous_potato")
    val map = ItemsMapping("map")
    val golden_carrot = ItemsMapping("golden_carrot")
    val skull = ItemsMapping("skull")
    val carrot_on_a_stick = ItemsMapping("carrot_on_a_stick")
    val nether_star = ItemsMapping("nether_star")
    val pumpkin_pie = ItemsMapping("pumpkin_pie")
    val fireworks = ItemsMapping("fireworks")
    val firework_charge = ItemsMapping("firework_charge")
    val enchanted_book = ItemsMapping("enchanted_book")
    val comparator = ItemsMapping("comparator")
    val netherbrick = ItemsMapping("netherbrick")
    val quartz = ItemsMapping("quartz")
    val tnt_minecart = ItemsMapping("tnt_minecart")
    val hopper_minecart = ItemsMapping("hopper_minecart")
    val armor_stand = ItemsMapping("armor_stand")
    val iron_horse_armor = ItemsMapping("iron_horse_armor")
    val golden_horse_armor = ItemsMapping("golden_horse_armor")
    val diamond_horse_armor = ItemsMapping("diamond_horse_armor")
    val lead = ItemsMapping("lead")
    val name_tag = ItemsMapping("name_tag")
    val command_block_minecart = ItemsMapping("command_block_minecart")
    val record_13 = ItemsMapping("record_13")
    val record_cat = ItemsMapping("record_cat")
    val record_blocks = ItemsMapping("record_blocks")
    val record_chirp = ItemsMapping("record_chirp")
    val record_far = ItemsMapping("record_far")
    val record_mall = ItemsMapping("record_mall")
    val record_mellohi = ItemsMapping("record_mellohi")
    val record_stal = ItemsMapping("record_stal")
    val record_strad = ItemsMapping("record_strad")
    val record_ward = ItemsMapping("record_ward")
    val record_11 = ItemsMapping("record_11")
    val record_wait = ItemsMapping("record_wait")
    val prismarine_shard = ItemsMapping("prismarine_shard")
    val prismarine_crystals = ItemsMapping("prismarine_crystals")
    val banner = ItemsMapping("banner")

}

class ItemsMapping(name: String): FieldMapping<Any, Items>(MapItems, name) {

}


open class Items protected constructor(original: Any) : WrapperClass(original) {
    companion object {
        val iron_shovel by MapItems.iron_shovel
        val iron_pickaxe by MapItems.iron_pickaxe
        val iron_axe by MapItems.iron_axe
        val flint_and_steel by MapItems.flint_and_steel
        val apple by MapItems.apple
        val bow by MapItems.bow
        val arrow by MapItems.arrow
        val coal by MapItems.coal
        val diamond by MapItems.diamond
        val iron_ingot by MapItems.iron_ingot
        val gold_ingot by MapItems.gold_ingot
        val iron_sword by MapItems.iron_sword
        val wooden_sword by MapItems.wooden_sword
        val wooden_shovel by MapItems.wooden_shovel
        val wooden_pickaxe by MapItems.wooden_pickaxe
        val wooden_axe by MapItems.wooden_axe
        val stone_sword by MapItems.stone_sword
        val stone_shovel by MapItems.stone_shovel
        val stone_pickaxe by MapItems.stone_pickaxe
        val stone_axe by MapItems.stone_axe
        val diamond_sword by MapItems.diamond_sword
        val diamond_shovel by MapItems.diamond_shovel
        val diamond_pickaxe by MapItems.diamond_pickaxe
        val diamond_axe by MapItems.diamond_axe
        val stick by MapItems.stick
        val bowl by MapItems.bowl
        val mushroom_stew by MapItems.mushroom_stew
        val golden_sword by MapItems.golden_sword
        val golden_shovel by MapItems.golden_shovel
        val golden_pickaxe by MapItems.golden_pickaxe
        val golden_axe by MapItems.golden_axe
        val string by MapItems.string
        val feather by MapItems.feather
        val gunpowder by MapItems.gunpowder
        val wooden_hoe by MapItems.wooden_hoe
        val stone_hoe by MapItems.stone_hoe
        val iron_hoe by MapItems.iron_hoe
        val diamond_hoe by MapItems.diamond_hoe
        val golden_hoe by MapItems.golden_hoe
        val wheat_seeds by MapItems.wheat_seeds
        val wheat by MapItems.wheat
        val bread by MapItems.bread
        val leather_helmet by MapItems.leather_helmet
        val leather_chestplate by MapItems.leather_chestplate
        val leather_leggings by MapItems.leather_leggings
        val leather_boots by MapItems.leather_boots
        val chainmail_helmet by MapItems.chainmail_helmet
        val chainmail_chestplate by MapItems.chainmail_chestplate
        val chainmail_leggings by MapItems.chainmail_leggings
        val chainmail_boots by MapItems.chainmail_boots
        val iron_helmet by MapItems.iron_helmet
        val iron_chestplate by MapItems.iron_chestplate
        val iron_leggings by MapItems.iron_leggings
        val iron_boots by MapItems.iron_boots
        val diamond_helmet by MapItems.diamond_helmet
        val diamond_chestplate by MapItems.diamond_chestplate
        val diamond_leggings by MapItems.diamond_leggings
        val diamond_boots by MapItems.diamond_boots
        val golden_helmet by MapItems.golden_helmet
        val golden_chestplate by MapItems.golden_chestplate
        val golden_leggings by MapItems.golden_leggings
        val golden_boots by MapItems.golden_boots
        val flint by MapItems.flint
        val porkchop by MapItems.porkchop
        val cooked_porkchop by MapItems.cooked_porkchop
        val painting by MapItems.painting
        val golden_apple by MapItems.golden_apple
        val sign by MapItems.sign
        val oak_door by MapItems.oak_door
        val spruce_door by MapItems.spruce_door
        val birch_door by MapItems.birch_door
        val jungle_door by MapItems.jungle_door
        val acacia_door by MapItems.acacia_door
        val dark_oak_door by MapItems.dark_oak_door
        val bucket by MapItems.bucket
        val water_bucket by MapItems.water_bucket
        val lava_bucket by MapItems.lava_bucket
        val minecart by MapItems.minecart
        val saddle by MapItems.saddle
        val iron_door by MapItems.iron_door
        val redstone by MapItems.redstone
        val snowball by MapItems.snowball
        val boat by MapItems.boat
        val leather by MapItems.leather
        val milk_bucket by MapItems.milk_bucket
        val brick by MapItems.brick
        val clay_ball by MapItems.clay_ball
        val reeds by MapItems.reeds
        val paper by MapItems.paper
        val book by MapItems.book
        val slime_ball by MapItems.slime_ball
        val chest_minecart by MapItems.chest_minecart
        val furnace_minecart by MapItems.furnace_minecart
        val egg by MapItems.egg
        val compass by MapItems.compass
        val fishing_rod by MapItems.fishing_rod
        val clock by MapItems.clock
        val glowstone_dust by MapItems.glowstone_dust
        val fish by MapItems.fish
        val cooked_fish by MapItems.cooked_fish
        val dye by MapItems.dye
        val bone by MapItems.bone
        val sugar by MapItems.sugar
        val cake by MapItems.cake
        val bed by MapItems.bed
        val repeater by MapItems.repeater
        val cookie by MapItems.cookie
        val filled_map by MapItems.filled_map
        val shears by MapItems.shears
        val melon by MapItems.melon
        val pumpkin_seeds by MapItems.pumpkin_seeds
        val melon_seeds by MapItems.melon_seeds
        val beef by MapItems.beef
        val cooked_beef by MapItems.cooked_beef
        val chicken by MapItems.chicken
        val cooked_chicken by MapItems.cooked_chicken
        val mutton by MapItems.mutton
        val cooked_mutton by MapItems.cooked_mutton
        val rabbit by MapItems.rabbit
        val cooked_rabbit by MapItems.cooked_rabbit
        val rabbit_stew by MapItems.rabbit_stew
        val rabbit_foot by MapItems.rabbit_foot
        val rabbit_hide by MapItems.rabbit_hide
        val rotten_flesh by MapItems.rotten_flesh
        val ender_pearl by MapItems.ender_pearl
        val blaze_rod by MapItems.blaze_rod
        val ghast_tear by MapItems.ghast_tear
        val gold_nugget by MapItems.gold_nugget
        val nether_wart by MapItems.nether_wart
        val potionitem by MapItems.potionitem
        val glass_bottle by MapItems.glass_bottle
        val spider_eye by MapItems.spider_eye
        val fermented_spider_eye by MapItems.fermented_spider_eye
        val blaze_powder by MapItems.blaze_powder
        val magma_cream by MapItems.magma_cream
        val brewing_stand by MapItems.brewing_stand
        val cauldron by MapItems.cauldron
        val ender_eye by MapItems.ender_eye
        val speckled_melon by MapItems.speckled_melon
        val spawn_egg by MapItems.spawn_egg
        val experience_bottle by MapItems.experience_bottle
        val fire_charge by MapItems.fire_charge
        val writable_book by MapItems.writable_book
        val written_book by MapItems.written_book
        val emerald by MapItems.emerald
        val item_frame by MapItems.item_frame
        val flower_pot by MapItems.flower_pot
        val carrot by MapItems.carrot
        val potato by MapItems.potato
        val baked_potato by MapItems.baked_potato
        val poisonous_potato by MapItems.poisonous_potato
        val map by MapItems.map
        val golden_carrot by MapItems.golden_carrot
        val skull by MapItems.skull
        val carrot_on_a_stick by MapItems.carrot_on_a_stick
        val nether_star by MapItems.nether_star
        val pumpkin_pie by MapItems.pumpkin_pie
        val fireworks by MapItems.fireworks
        val firework_charge by MapItems.firework_charge
        val enchanted_book by MapItems.enchanted_book
        val comparator by MapItems.comparator
        val netherbrick by MapItems.netherbrick
        val quartz by MapItems.quartz
        val tnt_minecart by MapItems.tnt_minecart
        val hopper_minecart by MapItems.hopper_minecart
        val armor_stand by MapItems.armor_stand
        val iron_horse_armor by MapItems.iron_horse_armor
        val golden_horse_armor by MapItems.golden_horse_armor
        val diamond_horse_armor by MapItems.diamond_horse_armor
        val lead by MapItems.lead
        val name_tag by MapItems.name_tag
        val command_block_minecart by MapItems.command_block_minecart
        val record_13 by MapItems.record_13
        val record_cat by MapItems.record_cat
        val record_blocks by MapItems.record_blocks
        val record_chirp by MapItems.record_chirp
        val record_far by MapItems.record_far
        val record_mall by MapItems.record_mall
        val record_mellohi by MapItems.record_mellohi
        val record_stal by MapItems.record_stal
        val record_strad by MapItems.record_strad
        val record_ward by MapItems.record_ward
        val record_11 by MapItems.record_11
        val record_wait by MapItems.record_wait
        val prismarine_shard by MapItems.prismarine_shard
        val prismarine_crystals by MapItems.prismarine_crystals
        val banner by MapItems.banner
    }
}
